---
deployment:
      tasks:
        - export DEPLOYPATH=../../junior_dev_website/
        - cp -r app $DEPLOYPATH
        - cp -r public ../../public_html/
        - cp -r node_modules $DEPLOYPATH
        - cp -r build $DEPLOYPATH
        - cp -r builds $DEPLOYPATH
        - cp -r vendor $DEPLOYPATH
        - cp -r writable $DEPLOYPATH
        - cp -r composer.json $DEPLOYPATH
        - cp -r composer.lock $DEPLOYPATH
        - cp -r package.json $DEPLOYPATH
        - cp -r LICENSE $DEPLOYPATH
        - cp -r package-lock.json $DEPLOYPATH
        - cp -r preload.php $DEPLOYPATH
        - cp -r spark $DEPLOYPATH 
        - cp -r phpunit.xml.dist $DEPLOYPATH  
        # need to change the upload paths and how things are aranged for stuff on site and stuff other people upload